fix Generator.scala to emit correct set of tests to be run by BOOM without an FPU
riscv-boom/riscv-boom pull request #142
Opened 2019-01-01 12:08 UTC by codelec

disabling fpu should show the correct set of supported extensions in dts

2019-01-01 16:09 UTC, jerryz123 requested changes

2019-01-01 16:09 UTC, jerryz123 commented on src/main/scala/common/configs.scala
> -      usingFPU = false))
Can we keep the flag as usingFPU instead of fpu for consistency with rocketchip?

2019-01-02 03:58 UTC, codelec commented on src/main/scala/common/configs.scala
> -      usingFPU = false))
setting fpu to None does disable `usingFPU` https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/tile/Core.scala#L54

2019-01-02 04:02 UTC, jerryz123 approved these changes

2019-01-02 04:07 UTC, jerryz123 commented
Thank you @codelec

2019-01-02 04:07 UTC, merged