[pnr] Initial simple point-of-no-return implementation in ROB
riscv-boom/riscv-boom pull request #193
Opened 2019-02-16 05:19 UTC by jerryz123

This is taken from work on the secureboom project.
A simple PNR head that advances one ROB row per cycle.
Currently drives nothing.

The LSU should eventually be able to mark loads as safe to eventually commit, when they are guaranteed to not cause a memory-ordering failure. This will substantially improve the run-ahead of the PNR.

2019-02-27 21:17 UTC, jerryz123 commented
@bkorpan If there are no concerns here I'd like to merge this.

2019-02-27 23:16 UTC, ccelio requested changes

2019-02-27 23:16 UTC, ccelio commented on src/main/scala/exu/rob.scala
> +   val pnr_head = UInt(ROB_ADDR_SZ.W)
I'm sorry this is nit-picky, but for consistency, should this be `rob_head`, `rob_pnr`, and `rob_tail`?

2019-02-27 23:16 UTC, ccelio commented on src/main/scala/exu/rob.scala
> +   assert(!(rob_head === WrapInc(pnr_head, num_rob_rows) && pnr_head =/= rob_tail),
Good assert. I'm wondering if there's another assert we can add to catch the scenario where we have an exception thrown on an entry marked "safe". We want to catch the scenario where the pnr erroneously advanced too far.

2019-02-27 23:16 UTC, ccelio commented on src/main/scala/lsu/lsu.scala
> +   io.ld_success_rob_idx := 0.U
Are these signals set to true anywhere? It doesn't look to me that the pnr_safe is being set for loads/stores as early as they can be.

2019-02-27 23:16 UTC, ccelio commented on src/main/scala/lsu/lsu.scala
> +   io.ld_success_rob_idx := 0.U
I see, your commit message explains this.

2019-02-27 23:21 UTC, ccelio commented
> The LSU should eventually be able to mark loads as safe to eventually commit, when they are guaranteed to not cause a memory-ordering failure. This will substantially improve the run-ahead of the PNR. I left a signal from the LSU to control this, but kept it tied off for now.

I don't think that's an issue. Loads are "safe" once their address is known. Sure... they might actually throw an ordering-violation exception, but in that scenario, an older load or store will be marked "unsafe" as its address isn't known yet. Once the older address is known, then the younger load notifies the ROB it will throw a "mini-exception" and it can clear its `rob_safe` at the same time. The only trick here is to verify the older load doesn't get marked unbusy and safe (so the ROB head and PNR can proceed) before the younger load can be marked "unsafe" (so the PNR can proceed).

2019-03-13 22:37 UTC, ccelio approved these changes
Thanks for addressing my feedback; this looks good to me.

2019-03-13 22:45 UTC, merged