Made fast wakeup broadcast to busytable optional.
riscv-boom/riscv-boom pull request #214
Opened 2019-03-01 19:33 UTC by bkorpan

2019-03-04 09:24 UTC, pentin-as commented
enablePipelinedAllocation = true,
enableFastWakeupsToRename = false,

/home/pentin-as/riscv/00001_titan/ext/ip/00003_riscv/sim/gen/mm.riscv started
C0: reg block 4x5x6, cache block 24x25x24
C0: 24810 instructions
C0: 17906 cycles
C0: 28800 flops
C0: 1608 Mflops @ 1 GHz
C0: c[0][4] %f != %f
benchmark failure
 ... failed, error code = 3

I'll try to figure out why.

2019-03-04 10:56 UTC, pentin-as commented
enablePipelinedAllocation = false,
enableFastWakeupsToRename = false,
works
enablePipelinedAllocation = true,
enableFastWakeupsToRename = true,
does not work

This PR works. The problem in https://github.com/riscv-boom/riscv-boom/pull/215.

2019-03-21 22:42 UTC, jerryz123 requested changes

2019-03-21 22:42 UTC, jerryz123 commented on src/main/scala/exu/core.scala
> +      if (wu_idx < num_irf_write_ports + 1)
This looks more hacky than I'd like. 

Can we tag the ExeUnitResp bundles with a "is_fast_wakeup" field, and then dynamically do this assignment here? We can add some asserts to make sure we have the number of fast and slow wakeups we expect.

2019-04-09 22:45 UTC, closed without merging