[rob] Get the PC from the FTQ when enqueuing exceptions to the ROB
riscv-boom/riscv-boom pull request #222
Opened 2019-03-16 03:41 UTC by jerryz123

Resolves #62

The ROB should receive the PC of enqueuing uops when one of those uops causes an exception. 
When the frontend sends an excepting uop, wait for the ROB to empty first. Then get the PC from the FTQ.

2019-03-16 07:54 UTC, ccelio requested changes
At a high-level, I don't see why you need to read the exception PC during decode; you can trivially grab it during commit. In fact, you should already have that commit port on the FTQ's PCFile because the CSRFile needs the commit PC (esp. for future RISC-V Standard Trace port stuff) and so does updating the predictors.

2019-03-16 07:54 UTC, ccelio commented on src/main/scala/exu/core.scala
> +                        || (dec_uops(w).exception
i don't think you can do this -- the exception signal will be very late arriving and the `stall_me` signal is driving a serialized chain of uops.

2019-03-19 20:53 UTC, ccelio requested changes
The trap value comes from two possibly places: 1) the ROB's badvaddr/tval (breakpoints, misaligned loads/stores, etc.) or 2) the FTQ's fetch-address (which gets passed to csr.io.pc). 

The csr.io.pc requires some clean-up to deduce what the actual PC of the current head-of-the-ROB is; if the instruction is split across FTQ entries (because it required two cycles to fetch all of the bits), the fetch-address coming from the FTQ needs to be readjusted to point to the first-half of the instruction; otherwise you simply add the low-order bits stored in the ROB to the fetch-address coming from the FTQ to get the exact `pc` of your particular, excepting instruction. 

The final corner case that gets weird is an instruction page fault for "split" instructions; you don't want to point to the PC of the failing instruction, you want to point to the VM page.

None of this requires recomputing jump/branch targets using instruction bits or opcodes; you only need to know the FTQ's fetch-address, the low-order PC bits, the exception cause, and is_split for the excepting instruction.

2019-03-19 20:53 UTC, ccelio commented on src/main/scala/exu/core.scala
> +   val tval_addr_pc = Mux((rob.io.com_xcpt.bits.uopc === uopJAL &&
In the ROB, you don't have access to uop.bits.uopc nor uop.bits.inst, so you can't compute the trap value PC in this manner.

2019-03-19 20:53 UTC, ccelio commented on src/main/scala/exu/core.scala
> +                          ComputeJALTarget(csr.io.pc, ExpandRVC(rob.io.com_xcpt.bits.inst), xLen),
The `inst` bits that enter the backend are already expanded; and they are thrown away before entering the ROB, so you can't compute the JAL target in this manner.

2019-03-22 23:00 UTC, jerryz123 commented
My

> The trap value comes from two possibly places: 1) the ROB's badvaddr/tval (breakpoints, misaligned loads/stores, etc.) or 2) the FTQ's fetch-address (which gets passed to csr.io.pc).
> 
> The csr.io.pc requires some clean-up to deduce what the actual PC of the current head-of-the-ROB is; if the instruction is split across FTQ entries (because it required two cycles to fetch all of the bits), the fetch-address coming from the FTQ needs to be readjusted to point to the first-half of the instruction; otherwise you simply add the low-order bits stored in the ROB to the fetch-address coming from the FTQ to get the exact `pc` of your particular, excepting instruction.
> 
> The final corner case that gets weird is an instruction page fault for "split" instructions; you don't want to point to the PC of the failing instruction, you want to point to the VM page.
> 
> None of this requires recomputing jump/branch targets using instruction bits or opcodes; you only need to know the FTQ's fetch-address, the low-order PC bits, the exception cause, and is_split for the excepting instruction.

In the case of !usingCompressed, wouldn't JAL instructions potentially throw misaligned_fetch exceptions? That is the case which is annoying, the target address needs to be regenerated using the inst bits and pc.

The case of a 32b instruction split across pages in RVC is already handled in the way edge_inst is set.

2019-03-22 23:08 UTC, aswaterman commented
The rocket core sets tval to 0 on misaligned-fetch exceptions for similar reasons.

The privileged spec says, "The hardware platform will specify which exceptions must set mtval informatively and which may unconditionally set it to zero."  In the absence of a platform spec, we've taken the interpretation that, since misaligned-fetch exceptions are not resumable, providing tval isn't especially useful to software, and so it's not worth going out of our way to support it.

2019-03-22 23:36 UTC, ccelio commented
Yes, my recommendation is to follow what Rocket does and set `tval=0` on misaligned-fetch. Technically you could shove the bad JAL's target into the next FTQ entry (it may already do this) but it's not worth the headache of accelerating an unrecoverable error.

2019-03-22 23:47 UTC, jerryz123 commented
What was the issue last year, which prompted you to add the hack? I see github issues referencing expanded ma_fetch test cases. It seems like setting tval=0 works with the current riscv-tests?

2019-03-22 23:52 UTC, ccelio commented
I don't remember; but I think I was trying to set tval to something and was getting it wrong, and didn't realize I could escape out by setting it to tval=0.

2019-03-22 23:57 UTC, closed without merging