[WIP] Feb. Rocket Bump
riscv-boom/riscv-boom pull request #239
Opened 2019-04-12 18:46 UTC by abejgonzalez

Add things needed to compile `boom` with the latest `rocket-chip` found in `boom-template`

2019-04-13 23:21 UTC, jerryz123 requested changes

2019-04-13 23:21 UTC, jerryz123 commented on src/main/scala/exu/fp-pipeline.scala
> +      fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, delay_by_one=true)
Can you make the parameter name "latency", and `require(latency == 1 || latency == 0)` inside `WritePort`. 

Then you can just make this 

`fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, regreadLatency)`

2019-04-13 23:49 UTC, abejgonzalez commented on src/main/scala/exu/fp-pipeline.scala
> +      fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, delay_by_one=true)
Will there ever be a case where the regreadlatency is > 1?  If so this, breaks down. While I agree this looks cleaner, it may break future functionality.

2019-04-14 00:11 UTC, jerryz123 commented on src/main/scala/exu/fp-pipeline.scala
> +      fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, delay_by_one=true)
https://github.com/riscv-boom/riscv-boom/blob/7fd7fe5b7eeffb835c649cdbf27e4b836de9335a/src/main/scala/common/parameters.scala#L156

Turns out `regreadLatency = 0` is unsupported. I'm in favor of removing all references to `regreadLatency = 0`, and removing that parameterization option.

2019-04-14 03:48 UTC, abejgonzalez commented on src/main/scala/exu/fp-pipeline.scala
> +      fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, delay_by_one=true)
Hmm. Im not sure this discussion should be done on a bump then. I think we should punt this change to another PR where we can discuss this a bit more.

2019-04-14 03:55 UTC, jerryz123 commented on src/main/scala/exu/fp-pipeline.scala
> +      fregfile.io.write_ports(0) <> WritePort(ll_wbarb.io.out, FPREG_SZ, fLen+1, delay_by_one=true)
Sure, I'll open an issue

2019-04-14 03:55 UTC, jerryz123 approved these changes

2019-04-14 04:50 UTC, merged