Common refactor
riscv-boom/riscv-boom pull request #281
Opened 2019-06-09 19:12 UTC by bkorpan

Refactored core configs in common/configs.scala

Replaced DefaultBoomConfig with BaseBoomConfig:
DefaultBoom was a bit of a nonsense config: essentially MediumBoom with a highly overprovisioned frontend and deeper speculation window. Should we turn BaseBoomConfig into a valid, minimalist config for debug? Can make SmallBoomConfig a more sensible design point if it no longer needs to be strictly debug-oriented.

4 core configs now: Small, Medium, Large and Huge which feature 1, 2, 3 and 4 -wide pipelines.

Style refactor of common package (spacing, braces, etc.)
This includes some renaming of signals & parameters used throughout the codebase.

2019-06-09 19:33 UTC, jerryz123 commented on src/main/scala/system/Configs.scala
> +  new WithMediumBooms ++
Is this in the right order?

2019-06-09 19:39 UTC, bkorpan commented on src/main/scala/system/Configs.scala
> +  new WithMediumBooms ++
> 
> 
> Is this in the right order?

No, but it doesn't actually matter right now. It will if we add some parameters to BaseBoomConfig which overlap with the core configs.

2019-06-09 19:47 UTC, jerryz123 commented
Is LargeBoomConfig appropriately sized for BEAGLE?

2019-06-09 20:00 UTC, bkorpan commented
> 
> 
> Is LargeBoomConfig appropriately sized for BEAGLE?

Probably not. It depends if we're willing to accept an additional 2 integer regfile read ports. Although, I suspect the 4-wide scheduling logic will be really nasty and become the new critical path.

2019-06-14 20:05 UTC, abejgonzalez commented on src/main/scala/common/configs.scala
> +  case BootROMParams => BootROMParams(contentFileName = s"./bootrom/bootrom.rv${site(XLen)}.img")
Can this move to a another mixin? Technically, the bootrom is not related to the core parameters and can change depending on what the configuration needs. Also... removing this makes it fall in line with what `project-template` does

2019-06-14 20:23 UTC, abejgonzalez commented on src/main/scala/system/Configs.scala
> +  new BaseBoomConfig ++
These should be swapped?

2019-06-14 20:24 UTC, jerryz123 requested changes

2019-06-14 20:24 UTC, jerryz123 commented on src/main/scala/lsu/lsu.scala
> -   val laq_addr_val       = Reg(Vec(NUM_LDQ_ENTRIES, Bool()))
Can you revert all the changes to LSU.scala, and add both NUM_LDQ_ENTRIES and numLdqEntries to the set of variables? Changing the naming here makes rebasing the LSU refactor painful. 
I'll change the naming in that PR.

2019-06-14 20:25 UTC, bkorpan commented on src/main/scala/system/Configs.scala
> +  new BaseBoomConfig ++
Good catch, I could have sworn I already fixed that.

2019-06-14 20:30 UTC, abejgonzalez commented on src/main/scala/system/Configs.scala
> +  new BaseBoomConfig ++
IMO. Having the `BaseBoomConfig` after the `WithNBoomCores` seems weird. Ontop of that, having `WithNBoomCores` specifying parameters that can override prior mixins, I feel like `WithNBoomCores` should just take the prior tile params specified and duplicate the tiles. i.e.

if (tile param prev. specified) -> duplicate those params N times
else -> create N generic cores

2019-06-14 20:37 UTC, abejgonzalez commented on src/main/scala/common/parameters.scala
> +  useNewFetchBuffer: Boolean = true,
If this is enabled then we should delete the old one.

2019-06-14 20:43 UTC, bkorpan commented on src/main/scala/common/parameters.scala
> +  useNewFetchBuffer: Boolean = true,
Another good catch, it should be disabled by default.

2019-06-14 20:45 UTC, abejgonzalez commented on src/main/scala/common/parameters.scala
> +  val pregSz          = ipregSz max fpregSz
Instead of overriding this in particular places, I would instead just rename this `maxPregSz` or something similar to that. Or rename the inner variable in the submodules to be something like `localPregSz`/`freelistPregSz`

2019-06-14 20:47 UTC, abejgonzalez commented on src/main/scala/system/Configs.scala
> +  new BaseBoomConfig ++
Now that I think of it... this might be hard to do without it getting overly confusing. I think for now having the `Base` config be after is fine until I think of a better solution.

2019-06-14 20:51 UTC, bkorpan commented on src/main/scala/common/parameters.scala
> +  val pregSz          = ipregSz max fpregSz
`maxPregSz` works

2019-06-19 19:07 UTC, abejgonzalez commented on src/main/scala/system/Configs.scala
> +class DualCoreMediumBoomAndDualRocketConfig extends Config(
While were at it, lets get rid of the "core" in the name. Or switch to "DualCoreMediumBoomAndDualCoreRocketConfig"

2019-06-20 16:54 UTC, abejgonzalez approved these changes
LGTM. I think this is ready to be merged in. We have time to adjust for the BEAGLE tapeout (plus this doesn't involve any RTL changes)

2019-06-22 16:50 UTC, jerryz123 approved these changes

2019-06-22 16:55 UTC, merged