Fixed ROB fullness tracking w.r.t. mispredicts
riscv-boom/riscv-boom pull request #298
Opened 2019-06-15 00:30 UTC by bkorpan

Make sure maybe_full is true after a mispredict.

2019-06-15 22:30 UTC, jerryz123 requested changes

2019-06-15 22:30 UTC, jerryz123 commented on src/main/scala/exu/rob.scala
> +  maybe_full := !rob_deq && (rob_enq || maybe_full) || io.brinfo.mispredict
Shouldn't this be `io.brinfo.valid && io.brinfo.mispredict`

2019-06-15 22:32 UTC, bkorpan commented on src/main/scala/exu/rob.scala
> +  maybe_full := !rob_deq && (rob_enq || maybe_full) || io.brinfo.mispredict
io.brinfo.mispredict can't go high without a valid brinfo packet.

2019-06-16 08:21 UTC, jerryz123 approved these changes

2019-06-16 08:21 UTC, merged