Connect Dromajo Simulator
riscv-boom/riscv-boom pull request #415
Opened 2019-11-19 19:45 UTC by abejgonzalez

**Related issue**: 

**Type of change**: new feature

**Impact**: new rtl

**Development Phase**: implementation

**Release Notes**
This adds the https://github.com/chipsalliance/dromajo simulator to BOOM for functional verification. However, this uses a fork of dromajo to do a couple things:

1. Override the MMIO start and end addresses
2. Override the Dromajo hard-coded bootrom with another
3. Override the Dromajo DTS with another
4. Change the reset vector
5. Have the bootrom be compact (aka. once the bootrom code is done, the dts is appended directly afterwards)

Here is the fork: https://github.com/abejgonzalez/dromajo/tree/loadable_bootrom

To get the simulation running here is an example command that I used to get bare-metal tests working:

`make run-binary CONFIG=SmallBoomConfig BINARY=output/example.TestHarness.SmallBoomConfig/rv64um-v-mul SIM_FLAGS="+drj_mmio_start=<HEX_NUM> +drj_mmio_end=<HEX_NUM> +drj_dtb_name=\"<DTB_FILE>\" +drj_binary_name=\"<BIN/CFG_FILE>\" +drj_bootrom_name=\"<BOOTROM_IMG>\""`

Since it is long, maybe it would be better to have a script wrap this?

Also, you need to change the VCS Makefile to include the following two lines in the compile:

```
<PATH-TO>/dromajo/src/libdromajo_cosim.a
-CC "-I<PATH-TO>/dromajo/src"
```

This was tested with bare-metal tests, I have yet to test this with Linux boot.

2019-11-19 19:46 UTC, abejgonzalez commented
I'll leave this open for people to leave comments, recommendations.

2019-11-19 20:58 UTC, jerryz123 requested changes

2019-11-19 20:58 UTC, jerryz123 commented on src/main/resources/csrc/dromajo_cosim.cc
> +    local_argv[local_argc] = (char*)"0x00010040";
Can we pass this in from `p(BootROMParams)` from the Chisel

2019-11-19 20:58 UTC, jerryz123 commented on src/main/resources/csrc/dromajo_cosim.cc
> +        local_argc += 1;
I feel like the bootrom and dtb should both be auto-specified somehow. It feels weird to need flags to point these to files, when at elaboration time we know where the files are.

2019-11-19 20:58 UTC, jerryz123 commented on src/main/resources/csrc/dromajo_cosim.cc
> +        local_argc += 1;
Is it possible to autogenerate this as well? At elaboration time we know where physical memory, and the bootrom are. Anything that is not in that region is "MMIO".

2019-11-19 20:58 UTC, jerryz123 commented on src/main/scala/common/consts.scala
> +  val DROMAJO_COSIM_ENABLE = true
What happens if you run without any dromajo flags and `DROMAJO_COSIM_ENABLE = true`. Does dromajo get linked in, and not run?

2019-11-19 20:59 UTC, jerryz123 commented
Great job, this looks very promising. 
We should think about how to integrate this into Chipyard cleanly. It would be great if we could just do `make CONFIG=DromajoSmallBoomConfig run-asm-tests` and have everything work.

2019-11-19 21:40 UTC, ccelio commented
Looks awesome! Please do PR some of your Dromajo changes so we can share improvements!

2019-11-19 22:03 UTC, abejgonzalez commented on src/main/scala/common/consts.scala
> +  val DROMAJO_COSIM_ENABLE = true
Dromajo will error out giving the usage string.

2019-11-19 22:04 UTC, abejgonzalez commented
@ccelio I will definitely PR the changes, I just want to get things cleaned up first!

2019-11-19 22:05 UTC, abejgonzalez commented on src/main/resources/csrc/dromajo_cosim.cc
> +    local_argv[local_argc] = (char*)"0x00010040";
Yes. That is the next step... I had a bit of changes to do this but I wanted to make sure things worked first before doing this.

2019-11-19 22:06 UTC, abejgonzalez commented on src/main/resources/csrc/dromajo_cosim.cc
> +        local_argc += 1;
Noted. And I agree.

2019-11-19 22:09 UTC, abejgonzalez commented on src/main/resources/csrc/dromajo_cosim.cc
> +        local_argc += 1;
The problem that I encountered with this is that there is only 1 MMIO region according to Dromajo. However, there are MMIO regions around the BOOTROM. Currently, I say MMIO_START=(After bootrom) MMIO_END=(Before MMIO_AXI4). That will cover the clint, $ controller, and the interrupt controller. Something more elegant would probably take more time.

2019-11-19 22:12 UTC, jerryz123 commented on src/main/resources/csrc/dromajo_cosim.cc
> +        local_argc += 1;
I see. In that case just auto-setting start to be the end of the bootrom and the end to be start of DRAM_BASE should be fine.

2019-11-21 18:35 UTC, ccelio commented
Does this turn off the DTM to prevent external agent/device polling?

2019-11-21 21:21 UTC, abejgonzalez commented
In Chipyard we use HTIF/TSI to bringup the core. I don't turn off the debug module.

2019-11-21 23:54 UTC, ccelio commented
How do you co-simulate if HTIF/TSI can perturb the state of the system? I would think you would also have to simulate the side-effects of the HTIF/TSI actions.

2019-11-22 00:00 UTC, jerryz123 commented
> How do you co-simulate if HTIF/TSI can perturb the state of the system? I would think you would also have to simulate the side-effects of the HTIF/TSI actions.

TSI only reads from the TOHOST addr in our systems. As long as it does no writes, we are good.

2019-11-25 06:22 UTC, abejgonzalez commented
@jerryz123 I went ahead and updated the release notes. Currently, you have to specify the binary and the dtb file with plusargs. Unfortunately, I don't think there is a way to make the binary plusarg go away. VCS doesn't have a default variable of some sort that I can check and get the binary file. As for the dtb, I need to modify Chipyard so Ill leave that for a later time since that is a bit ugly. Until that is fixed you can do `dtc -O dtb *.dts -o *.dtb` to get the dtb to point to.

2019-11-25 06:23 UTC, abejgonzalez commented
Also, I will remove the default `COSIM = true` constant once CI finishes, I just want to make sure Verilator compiles with this.

2019-11-26 02:13 UTC, jerryz123 commented
> @jerryz123 I went ahead and updated the release notes. Currently, you have to specify the binary and the dtb file with plusargs. Unfortunately, I don't think there is a way to make the binary plusarg go away. VCS doesn't have a default variable of some sort that I can check and get the binary file. As for the dtb, I need to modify Chipyard so Ill leave that for a later time since that is a bit ugly. Until that is fixed you can do `dtc -O dtb *.dts -o *.dtb` to get the dtb to point to.

The DTB thing is fine for now. Can we really not get the args with `vpi_get_vlog_info`? https://github.com/ucb-bar/testchipip/blob/master/src/main/resources/testchipip/csrc/SimSerial.cc does this.

Also can you merge some intermediate commits, and prepend them with [cosim].

2019-11-26 18:45 UTC, abejgonzalez commented
Done @jerryz123. This should be ready for review now... assuming CI passes.

2019-11-27 19:29 UTC, jerryz123 approved these changes

2019-11-27 19:29 UTC, jerryz123 commented on src/main/scala/exu/core.scala
> +          Mux(uop.is_rvc, Cat(0.U(16.W), uop.debug_inst(15,0)), uop.debug_inst)
According to https://github.com/chipsalliance/dromajo/blob/d8689621645be0270f324cdac3c5778f4628def3/src/dromajo_cosim.h#L50-L52 Dromajo expects only expanded (non-RVC) instructions. Shouldn't there be a `ExpandRVC` block in here?

2019-11-27 19:34 UTC, jerryz123 commented on src/main/resources/csrc/dromajo.h
> +
Dromajo itself has a file called dromajo.h. How are we sure that VCS includes this file, instead of that one, whenever `#include "dromajo.h"` appears? 
Can we consolidate these headers and csrc files into just two, with non-conflicting names? "dromajo_boom.cc" and "dromajo_boom.h", for example.

2019-11-28 00:14 UTC, abejgonzalez commented on src/main/scala/exu/core.scala
> +          Mux(uop.is_rvc, Cat(0.U(16.W), uop.debug_inst(15,0)), uop.debug_inst)
Hmm. So while that might be true... Dromajo does support the C extension in-general. Also, how would Linux boot pass and baremetal RVC tests pass if wasn't supported? I would figure that I should've seen this error earlier.

2019-11-28 00:17 UTC, abejgonzalez commented on src/main/resources/csrc/dromajo.h
> +
Well not putting it causes a compilation error. I can make it clearer though. As for combining the two... I think if this eventually moves to a new location (i.e. Chipyard), it would make sense to have the `dromajo_cosim` file be different from the `dromajo` file since the `cosim` file is particular to BOOM while the `dromajo` files are not.

2019-11-28 00:53 UTC, jerryz123 commented on src/main/scala/exu/core.scala
> +          Mux(uop.is_rvc, Cat(0.U(16.W), uop.debug_inst(15,0)), uop.debug_inst)
Huh thats weird. Its possible that dromajo comment is out-of-date. If `rv64uc-p-rvc` passes with Domajo then I guess its fine.

2019-11-28 00:54 UTC, jerryz123 commented on src/main/resources/csrc/dromajo.h
> +
My point is that its a little confusing to have multiple `dromajo.h` and `dromajo.cc` files floating around. We should rename the failes we include in BOOM to not have name conflicts with the ones provided by dromajo.

2019-11-28 00:55 UTC, jerryz123 commented on src/main/scala/exu/core.scala
> +          Mux(uop.is_rvc, Cat(0.U(16.W), uop.debug_inst(15,0)), uop.debug_inst)
Huh I guess the dromajo comment is out-of-date. If it passes `rv64uc-p-rvc` then its fine.

2019-11-28 00:57 UTC, jerryz123 commented on src/main/resources/csrc/dromajo.h
> +
My point is that there's a naming conflict between files you added here and the dromajo source files. You defined a new `dromajo.cc`, `dromajo.h`, and `dromajo_cosim.cc`, and those files also exist as dromajo source files. Regardless of where these newly defined files live, they should be named to not conflict with the dromajo source files, to avoid confusion.

2019-11-28 06:22 UTC, abejgonzalez commented on src/main/resources/csrc/dromajo.h
> +
Done

2019-11-28 06:36 UTC, abejgonzalez commented on src/main/scala/exu/core.scala
> +          Mux(uop.is_rvc, Cat(0.U(16.W), uop.debug_inst(15,0)), uop.debug_inst)
I ran the two asm tests with RVC and both passed so I think the comment is out-of-date.

2019-11-28 06:36 UTC, abejgonzalez commented
I am running all assembly/bmark tests with Dromajo and I am encountering divergences (I will look into it after Thanksgiving break).

2019-12-03 01:59 UTC, abejgonzalez commented
Ok. I resolved/figured out most of the divergences... here they are:

`rv64mi-p-mcsr` - `mimpid`, `marchid`, `mvendorid` are all set to specific values by Dromajo by default. This has no large impact.
`rv64mi-p-breakpoint` - this test fails unless you add one breakpoint, additionally if you set `nBreakpoints` to `true` then it will error since Rocket sets its `maskmax` reset value to `4` by default while Dromajo has it unset.
`rv64ua-v-lrsc` - bug with BOOM. see #417 
all benchmark tests - all fail due to `tohost`/`fromhost` issues (additionally, this only works with non-randomized memory init)

2019-12-03 22:17 UTC, ccelio commented
> (additionally, this only works with non-randomized memory init)

**TL,DR:** I think you have to disable randomized memory.

The problem is that some of the riscv-tests will access memory that has not been initialized first (for example, a load-reserve that doesn't care about what it is actually loading). Unless you randomize dramajo with the exact same memory pattern from boom, there's no hope of this really working (aside from expensively tracking whether each byte has been accessed yet, and if not, letting the DUT override dramajo, which means you have the same coverage hole anyways). 

This gets extra complicated because elf binaries have a `bss` section which is generally assumed to be zeroed out by software. To save on elf space, the `bss` simply says "I am X bytes in size". This requires the elf loader to do the zeroing. I don't remember if elf2hex does this bss zeroing, because the bss section can be large.

For this reason, I recommend zeroing out all DUT memory. It's a small loss in coverage, but a huge removal of headaches.

2019-12-03 22:21 UTC, jerryz123 commented
> For this reason, I recommend zeroing out all DUT memory. It's a small loss in coverage, but a huge removal of headaches.

Yeah adding `+define+RANDOM=0` to the VCS CCFLAGS is sufficient for this.

2019-12-03 22:25 UTC, ccelio commented
> Yeah adding +define+RANDOM=0 to the VCS CCFLAGS is sufficient for this.

Is that too heavy-handed, or does that only affect the bootROM/bootRAM and simRAM? I believe in the past I used a modified simRAM/bootRAM model that zeroed out the memory, but let other SeqMems and Regs be randomized (which is nice for X-prop/reset bug hunting).

Doing so is not unrealistic, since in the "real thing", you can freely zero out the bootRAM anyways.

2019-12-03 22:39 UTC, jerryz123 commented
Unfortunately it does cause all regs to be zero initialized, which is annoying. I think we would like to continue using the SimAXIMem for the simRAM, which does not let us specifically zero out that memory.

2019-12-03 22:48 UTC, ccelio commented
I’d consider pushing upstream a “zeroing” option to SimAXIMem (perhaps as a verilog define flag?).

2019-12-03 23:54 UTC, abejgonzalez commented
Yes. I ended up using the `+define+RANDOM=0` hack to get around this. We will just end up using that hack for Linux boot for now.

2019-12-04 01:50 UTC, abejgonzalez commented
This should be good to merge now.

2019-12-04 19:18 UTC, jerryz123 commented
This looks good to merge, but there's lots of opportunity for more features.

- We should do a bit more testing. How far does BOOM get in linux boot now?
- For the `tohost/fromhost` thing, it might be straightforward to modify Dromajo to consider those addresses to be "MMIO". Dromajo should have its own elfreader, so it should be able to determine the tohost/fromhost addresses when reading the binary.
- Can Dromajo be modified to simulate interactions with the block device? The key is that we don't need to simulate the entire device, we only need to simulate the sequence of stores the block device writes into RAM.
- Can the DromajoCosimBlackBox be modified to work as a Firesim bridge?

2019-12-04 19:38 UTC, abejgonzalez commented
> This looks good to merge, but there's lots of opportunity for more features.

Ill go ahead and make a GH issue to track improvements. But I think this is a good stepping stone to merge in for basic support.

> * We should do a bit more testing. How far does BOOM get in linux boot now?

I tested Linux boot (br-base + fedora + coremark) on FireSim. I haven't retried booting with Dromajo cosim. Though at the time, the failure was that uninitialized memory was getting read in. So I don't expect an issue.

> * For the `tohost/fromhost` thing, it might be straightforward to modify Dromajo to consider those addresses to be "MMIO". Dromajo should have its own elfreader, so it should be able to determine the tohost/fromhost addresses when reading the binary.

I think we can just ignore any errors related to `to/fromhost` instead of hacking Dromajo to make them MMIO. 

> * Can Dromajo be modified to simulate interactions with the block device? The key is that we don't need to simulate the entire device, we only need to simulate the sequence of stores the block device writes into RAM.

Future work!

> * Can the DromajoCosimBlackBox be modified to work as a Firesim bridge?

Future work!

2019-12-04 19:42 UTC, jerryz123 commented
> I tested Linux boot (br-base + fedora + coremark) on FireSim. I haven't retried booting with Dromajo cosim. Though at the time, the failure was that uninitialized memory was getting read in. So I don't expect an issue.

Sorry, I meant how far does it get when run with cosim? Can you start up a SW sim run with cosim, and the boot-binary?

2019-12-04 19:58 UTC, abejgonzalez commented
> Sorry, I meant how far does it get when run with cosim? Can you start up a SW sim run with cosim, and the boot-binary?

Running as we speak!

2019-12-10 00:23 UTC, jerryz123 approved these changes

2019-12-10 01:06 UTC, abejgonzalez commented
As an update... we think this is good to merge. Linux tests are finding small bugs here and there which means this is working! So we will go ahead and merge after CI.

2019-12-10 05:02 UTC, merged