icache: vaddr to index the cache for lookups and refills
riscv-boom/riscv-boom pull request #72
Opened 2018-04-20 21:49 UTC by ss2783

Currently, the icache uses the physical address to compute the tag
index for tag checks and the refills which restricted the ways to
be upto 4KB. This commit allows for ways to be larger than 4KB.
NOTE: The scratchpad behavior should be mostly not affected.

2018-04-20 21:56 UTC, ccelio commented on src/main/scala/ifu/icache.scala
> +  //require(!usingVM || pgIdxBits >= untagBits)
delete.

2018-04-20 21:57 UTC, ccelio commented on src/main/scala/ifu/icache.scala
>    val refill_addr = RegEnable(io.s1_paddr, s1_valid && !(refill_valid || s2_miss))
rename to `refill_paddr`.

2018-04-20 21:57 UTC, ccelio requested changes
Awesome!

2018-04-20 22:25 UTC, aswaterman commented
I suspect this is incorrect for the scratchpad functionality.

2018-04-20 23:46 UTC, ccelio commented
Thanks for the review and heads up @aswaterman. The scratchpad is vestigial for BOOM, so hopefully this shouldn't be an issue.

2018-04-21 16:58 UTC, ccelio approved these changes

2018-04-21 16:58 UTC, merged